// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsVa6S-y6ZOKTITFtzVbOKTXCX_qaVFtU',
    appId: '1:472709442599:web:a5286cf1afc5617dc5f202',
    messagingSenderId: '472709442599',
    projectId: 'berryclub',
    authDomain: 'berryclub.firebaseapp.com',
    storageBucket: 'berryclub.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvLnHNQLHm3TCOjrP0Iu2gTn5fDZK7F_I',
    appId: '1:472709442599:android:ae9078768533021dc5f202',
    messagingSenderId: '472709442599',
    projectId: 'berryclub',
    storageBucket: 'berryclub.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU8A1E1IKgws12B61Gl1dR-LjgMfIxPg0',
    appId: '1:472709442599:ios:3c4c6abcc7a57e39c5f202',
    messagingSenderId: '472709442599',
    projectId: 'berryclub',
    storageBucket: 'berryclub.appspot.com',
    iosClientId: '472709442599-3ct5sgd17q417ssub6mq1hr34m0dcf1e.apps.googleusercontent.com',
    iosBundleId: 'com.example.berryClub',
  );
}
